/**
 * Client product & brand imagery for Candle Artistry Design.
 * Files live in /public/images — prefix with Vite base for subdirectory hosts.
 */
const img = (file: string) => `${import.meta.env.BASE_URL}images/${file}`;

export const images = {
  logo: img("logo.png"),
  hero: img("hero.jpg"),
  heroBanner: img("hero-banner.jpg"),
  romance: img("romance.jpg"),
  west: img("west.jpg"),
  mystery: img("mystery.jpg"),
  cabin: img("cabin.jpg"),
  wilderness: img("wilderness.jpg"),
  experience1: img("experience-1.png"),
  experience2: img("experience-2.png"),
  experience3: img("experience-3.png"),
  experience4: img("experience-4.png"),
  experienceRomance: img("experience-romance-vivid.png"),
  experienceMystery: img("experience-mystery-vivid.png"),
  experienceCabin: img("experience-cabin-vivid.png"),
  experienceWilderness: img("experience-wilderness-vivid.png"),
  experienceClassic1: img("experience-classic-1.png"),
  experienceClassic2: img("experience-classic-2.png"),
  experienceClassic3: img("experience-classic-3.png"),
  experienceClassic4: img("experience-classic-4.png"),
  featuredMain: img("featured-main.jpg"),
  featuredRoyalStill: img("featured-royal-still.jpg"),
  featuredStrip1: img("strip-1.jpg"),
  featuredStrip2: img("strip-2.jpg"),
  featuredStrip3: img("strip-3.jpg"),
  artistryBg: img("artistry-bg.jpg"),
  paintings: img("paintings.jpg"),
  candles: img("candles.jpg"),
  cards: img("cards.jpg"),
  cards2: img("cards-2.png"),
  cards3: img("cards-3.png"),
  cards4: img("cards-4.png"),
  pouring: img("pouring.jpg"),
  productsGroup: img("products-group.png"),
  craftRomance: img("craft-romance.jpg"),
  craftRodeo: img("craft-rodeo.jpg"),
  craftVampire: img("craft-vampire.jpg"),
  craftAtelier: img("craft-atelier.jpg"),
  lifestyle: img("lifestyle.png"),
  vampire: img("vampire.png"),
  rodeoDetail: img("rodeo-detail.png"),
  testing: img("testing.png"),
  box: img("box.svg"),
  archBorder: img("decor/arch-border-gold.png"),
  botanical: img("decor/botanical-gold.png"),
  floralCorner: img("decor/floral-corner.png"),
  familyMotherDaughter: img("family/mother-daughter.jpg"),
  familyFatherDaughter: img("family/father-daughter.jpg"),
  familyDaughterGarden: img("family/daughter-garden.jpg"),
} as const;
